project_name: memtree
project_path: "/var/lib/{{ project_name }}"
logs_path: "/var/log/{{ project_name }}"
project_owner: www-data
project_group: www-data
venv_dir: "{{ project_path }}/venv"
asgi_module: "{{ project_name }}.asgi"
static_root: "{{ project_path }}/static"
cert_path: /etc/nginx/certificate.pem
key_path: /etc/nginx/certificate.key
redis_bind: 127.0.0.1
redis_port: 6379